steps:
  - id: 'dummy api install dependencies'
    name: python
    dir: 'fst/dummy_api'
    entrypoint: 'pip'
    args: ["install", "flask", "flask-restful", "pytest", "jsonschema", "--user"]

  - id: 'dummy api unit test'
    name: python
    dir: 'fst/dummy_api'
    entrypoint: 'python'
    args: ["-m", "pytest"]
    env:
      - 'PYTHONPATH=/workspace/fst/dummy_api/src'

  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    dir: 'fst/dummy_api'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dummy-api:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dummy-api:$SHORT_SHA'
      - '-f'
      - '/workspace/fst/dummy_api/Dockerfile'
      - '.'

  - id: 'Push Image'
    name: 'gcr.io/cloud-builders/docker'
    dir: 'fst/dummy_api'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          # Develop branch
          if [ $BRANCH_NAME = "develop" ]; then
            docker push gcr.io/$PROJECT_ID/dummy-api:$SHORT_SHA

          # Main branch
          elif [ $BRANCH_NAME = "main" ]; then
            docker push gcr.io/$PROJECT_ID/dummy-api:$SHORT_SHA

          # Another branch
          else
            echo "Branch name : $BRANCH_NAME"
          fi
