apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: mlflow-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      serviceAccountName: mlflow-sa
      containers:
      - name: mlflow-server
        image: python:3
        workingDir: /workdir
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mlflow-backend-db
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-backend-db
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-backend-db
              key: password
        command:
        - "/bin/sh"
        - "-c"
        - "pip install --upgrade pip; \
           pip install mlflow; \
           pip install mysqlclient; \
           pip install google-cloud-storage; \
           mlflow server \ 
           --backend-store-uri \
           mysql://$MYSQL_USER:$MYSQL_PASSWORD@mlflow-backend-db/$MYSQL_DATABASE \
           --default-artifact-root gs://fx-systemtrader-dev-artifacts/artifacts \
           --host 0.0.0.0"
        ports:
        - containerPort: 5000
          hostPort: 5000
