apiVersion: v1
kind: Service
metadata:
  name: mlflow-backend-db
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: mlflow-backend-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-backend-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-backend-db
  template:
    metadata:
      labels:
        app: mlflow-backend-db
    spec:
      containers:
      - name: mlflow-backend-db
        image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-backend-db
              key: root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mlflow-backend-db
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-backend-db
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-backend-db
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mlflow-backend-db
          mountPath: /var/lib/mysql
      volumes:
      - name: mlflow-backend-db
        persistentVolumeClaim:
          claimName: mlflow-backend-db-pvc
