apiVersion: v1
kind: Pod
metadata:
  name: my-gpu-pod
spec:
 containers:
 - name: my-gpu-container
   image: nvidia/cuda:10.0-runtime-ubuntu18.04
   command: ["nvidia-smi"]
   resources:
     limits:
       nvidia.com/gpu: 1
 restartPolicy: Never
