apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: argo-tutorial-sa@fx-systemtrader-dev.iam.gserviceaccount.com
  name: argo-tutorial-sa
  namespace: argo
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: argo
  name: argo-tutorial-sa-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-tutorial-sa-role-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argo-tutorial-sa 
  namespace: argo
roleRef:
  kind: Role 
  name: argo-tutorial-sa-role 
  apiGroup: rbac.authorization.k8s.io
